### PR TITLE
Issue #4  Activate SDA parts

### PR DESCRIPTION
**Pull request by jaewooan**
To resolve Issue #4, following modification is done:

1) Calculate update_formula for EDFM and pEDFM.
2) Modify the part for calculation of volumetric average distance.
3) Remove m_data.gmcell_to_flowcells.clear. 
    If we do m_data.gmcell_to_flowcells.clear, this erases edfm fracture cell id previously saved in 
    gmcell_to_flowcells by the function map_mechanics_to_control_volumes.

Please check it and give me your comment on this!

### CODE REVIEW

**Comment by ishovkun** [comment]
Jaewoo, I am not convinced that we need to use the structure GMCELL_TO_FLOWCELL to store the mapping of sda cells to fracture control volumes. This whole assumption of the ordering does not make any sense to me. Why don't we just make a separate structure SDACELL_TO_FRACTURECELL for this type of storage? This will totally eliminate the ordering assumptions and make the workflow more versatile.

**Comment by jaewooan** [comment]
Igor, do you mean it is better to define the SDACELL_TO_FRACTURECELL variable in MSH2GPRS or make a new keyword SDACELL_TO_FRACTURECELL for ADGPRS?

**Comment by ishovkun** [comment]
Yes, that's what I mean.

**Comment by ishovkun** [comment]
Wait. Maybe there can be even a better way.

**Comment by jaewooan** [comment]
I think those ideas seem clear. (although we need to add some codes related to new keywords in AD-GPRS). Anyway I am waiting for your comment!

**Comment by ishovkun** [comment]
Can we make something like GM_EFRAC_TO_FLOWCELL.
The entries in this vector the have a one-to-one correspondence to GM_EFRAC_CELLS.
I will post an example:
photo5688139221377853360

**Comment by ishovkun** [comment]
In GM_EFRAC_TO_FLOWCELL the order of entries is identical to that in GM_EFRAC_CELLS. Each entry has first number - number of connected flow cells, followed by the indices of the flow cells.
Does it make sense?

**Comment by jaewooan** [comment]
Gotcha, I will make this and push the modified one again.

**Pull request closed without merging**
